Completed prep-javascript-objects.
m-Cho1/prep-0122-code-solutions pull request #11
Opened 2022-01-18 22:17 UTC by m-Cho1

![prep-javascript-objects](https://user-images.githubusercontent.com/96744088/150027538-72d54db1-a54a-4629-907a-7f8d7c1f4d04.jpg)

2022-01-18 23:49 UTC, thebearingedge requested changes

2022-01-18 23:49 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +};
You can add new properties to an object later in a program using dot notation.

```js
person.job = 'Accountant';
```

2022-01-19 00:15 UTC, m-Cho1 commented on prep-javascript-objects/main.js
> +};
![prep-javascript-objects](https://user-images.githubusercontent.com/96744088/150039484-04faa51e-81a5-4f56-b0e0-8e9e3f0aef8c.jpg)

2022-01-19 00:24 UTC, m-Cho1 commented on prep-javascript-objects/main.js
> +};
![prep-javascript-objects](https://user-images.githubusercontent.com/96744088/150040278-278e4596-6b48-49ee-a61e-54407baf1e0e.jpg)
edited!

2022-01-19 00:28 UTC, m-Cho1 reviewed
![prep-javascript-objects](https://user-images.githubusercontent.com/96744088/150040605-88603732-640f-49fc-95fc-60b9f5bc6338.jpg)

2022-01-19 23:53 UTC, thebearingedge approved these changes

2022-01-19 23:58 UTC, merged